name: Build

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgl1-mesa-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build
        run: cmake --build build --config Debug
        timeout-minutes: 5

      - name: Run Linter and Formatter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          tidy-checks: ''
          extensions: 'c,cpp,h,hpp'
          files-changed-only: true
      - name: Fail fast?
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "Some files failed the linting and formatting checks!" && exit 1
